### ISSUE TITLE
How to obtain discovered subtrees

### ISSUE THREAD

**Issue by a3lem** [yunchi/CMTreeMiner_Unordered#2]
Hi, I'd like to try out this algorithm and its variants. My objective is to obtain a list of relevant subtrees. Unfortunately, neither the README nor the example output.txt suggests that such a list should be expected as output. That contrasts with available implementations of simpler alternatives, such as https://github.com/zakimjz/TreeMiner and http://chasen.org/~taku/software/freqt/.

Any tips on how to get the discovered subtrees as output?

PS Thanks for your paper _Frequent Subtree Mining — An Overview_ (2005). Sure, it's an old paper, but I was able to find my footing much faster thanks to it.

**Comment by yunchi** [comment]
Hi, I haven't touched that code for many years. However, I was able to find the following from a previous email:
"If it's the CMOrderedTreeMiner package (i.e., for mining ordered trees), then the solution is simple: at the end of file "OccLongList.cpp", there are two "cout << ..." lines that were commented out. Turn them on to output the trees."

However, since you are using the "unordered" version of CMTreeMiner, you may have to inject the "cout << ..." commands by yourself. You can look at the RDFCFTree.cpp and RBFCFTree.cpp, search for term "if (isClosed)" and "if (isMaximal)", and then add "cout << ..." there.

Hope this helps.

**Comment by a3lem** [comment]
Wow, didn't expect such a fast reply. Thanks!

I think I've more or less got it work. Took some digging around, since the variable names are different than in the Ordered variant. Also, the comment at the end of _CMTreeMiner.cpp_ seems to suggest that _RBFCFTree.cpp_ isn't used, but my C++ knowledge isn't good enough to verify whether this is the case.

For future wanderers, here's what I did. In _RDFCFTree.cpp_, go to the method definition `RDFCFTree::closedExtensionExplore` and locate the if-statements `if (isClosed == true)` and (further down) `if (isMaximal == true)`. To the body of the each if-statement, add the following:

```
maximal[vCount]++;
cout << "type=maximal; id=" << vCount << "; ";  # !! <- 'maximal' or 'closed', depending on the condition being checked.
cout << "support=" << occList.size() << "; ";
cout << "cs=";
for ( short i = 0; i < canonicalString.size(); i++ )
{
  cout << canonicalString[i] << " ";
}
cout << endl;
```

The canonical strings now appear on stdout.

Only **caveat** is that for some strange reason the canonical strings are sometimes empty. I'm still trying to figure out whether this is expected behavior or some error on my part. There's a good chance that it's the second, because I'm by no means familiar with C++. By contrast, CMTreeMiner\__Unordered_, does produce well-formed canonical strings (after reintroducing the commented-out lines mentioned in the post above).
